# Generated by Django 2.2.7 on 2020-01-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(default='New', max_length=2),
        ),
    ]
