# Generated by Django 2.2.7 on 2020-01-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrace', '0002_auto_20200106_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('n', 'New'), ('ip', 'In Progress'), ('f', 'Finished'), ('iv', 'Invalid')], default='n', max_length=2),
        ),
    ]
